#!/bin/bash
water_dec=$(echo "ibase=water; $WATER" | bc)
stir_dec=$(echo "ibase=stir; $STIR" | bc)

sum_dec=$(($water_dec + $stir_dec))

BESTCHOL=$(echo "obase=bestchol; $sum_dec" | bc)

echo "The sum of WATER and STIR is: $BESTCHOL"

